/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package miniprojet;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Prduit extends javax.swing.JPanel {
    public Double stcok_qty = 0.0;
     public static String filename = "";
      public static String pname = "";
    public Prduit() {
        initComponents();
         initComponents();
        tb_load();
        supplier_load();
        Price();
        verif(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     public void verif(){
        try{
            String name = Pname.getText();          
            Statement s = Bd.mycon().createStatement();
            ResultSet rs = s.executeQuery("SELECT Product_name FROM product");
            while (rs.next()){
                if (name.equals(rs.getString("Product_name"))){
                   Statement ss = Bd.mycon().createStatement();
                   ResultSet rs1 = ss.executeQuery(" SELECT Qty FROM product WHERE Product_name = '"+name+"' ");
                   while (rs1.next()){
                    stcok_qty = Double.valueOf(rs.getString(("Qty")));
                }
                    Double qty = Double.valueOf(Pqty.getText());
                    Double newqty = stcok_qty ;
                    Double new_qty = newqty + qty ;
                    String nqty = String.valueOf(new_qty);
                    Statement ss1 = Bd.mycon().createStatement();
                    ss1.executeUpdate(" UPDATE product SET Qty = '"+nqty+"' WHERE Product_name = '"+name+"' ");
                }
            }
        }catch(Exception e){           
        }
    }    
    public void Price(){
        try{
        Double cprice= Double.valueOf(Pcprice.getText());
        Double price = 0.0;
        Double Tva = Double.valueOf(tva.getText());
        
        price = (cprice*Tva/100)+cprice ;
        Pprice.setText(String.valueOf(price));
        
        }catch(Exception e){
            System.out.println(e);
        } 
    }    
    public void tb_load(){
    try{
        DefaultTableModel dt = (DefaultTableModel) Ptable.getModel();
        dt.setRowCount(0);
        Statement s = Bd.mycon().createStatement();
        ResultSet rs = s.executeQuery(" SELECT * FROM product ");
        while (rs.next()){
            Vector v = new Vector ();
            v.add(rs.getString(1));
            v.add(rs.getString(2));
            v.add(rs.getString(3));
            v.add(rs.getString(4));
            v.add(rs.getString(5));
            v.add(rs.getString(6));
            v.add(rs.getString(7));
            v.add(rs.getString(8));
            v.add(rs.getString(9));
            v.add(rs.getString(10));
            dt.addRow(v);
        }
    } catch(Exception e){
    System.out.println(e);
     }
    }
  public void supplier_load(){
        try{            
            Statement s = Bd.mycon().createStatement();
            ResultSet rs = s.executeQuery(" SELECT * FROM supplier ");
            Vector v = new Vector ();
            while(rs.next()){
            v.add(rs.getString("Supplier_name"));
            DefaultComboBoxModel cm = new DefaultComboBoxModel(v);
            Psn.setModel(cm);
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Psid = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        Pname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Bsave = new javax.swing.JButton();
        Bsearch = new javax.swing.JButton();
        Bupdate = new javax.swing.JButton();
        Bdelete = new javax.swing.JButton();
        Pcb = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        Pqty = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Psup = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        Pcategory = new javax.swing.JTextField();
        Pcprice = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        Psn = new javax.swing.JComboBox<>();
        tva = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        Pprice = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        Psname = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ptable = new javax.swing.JTable();
        Pst = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Produit:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 3, 16), new java.awt.Color(190, 156, 199))); // NOI18N

        Psid.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        Psid.setForeground(new java.awt.Color(190, 156, 199));
        Psid.setText("ID:");
        Psid.setToolTipText("");
        Psid.setBorder(null);
        Psid.setDisabledTextColor(new java.awt.Color(151, 153, 155));
        Psid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PsidActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Psid, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Psid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Pname.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        Pname.setForeground(new java.awt.Color(190, 156, 199));
        Pname.setText("Name:");
        Pname.setToolTipText("");
        Pname.setBorder(null);
        Pname.setDisabledTextColor(new java.awt.Color(151, 153, 155));
        Pname.setDragEnabled(true);
        Pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PnameActionPerformed(evt);
            }
        });
        Pname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PnameKeyReleased(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        Bsave.setBackground(new java.awt.Color(190, 156, 199));
        Bsave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bsave.setText("Save");
        Bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsaveActionPerformed(evt);
            }
        });

        Bsearch.setBackground(new java.awt.Color(190, 156, 199));
        Bsearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bsearch.setText("Search");
        Bsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsearchActionPerformed(evt);
            }
        });

        Bupdate.setBackground(new java.awt.Color(190, 156, 199));
        Bupdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bupdate.setText("Update");
        Bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BupdateActionPerformed(evt);
            }
        });

        Bdelete.setBackground(new java.awt.Color(190, 156, 199));
        Bdelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bdelete.setText("Delete");
        Bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdeleteActionPerformed(evt);
            }
        });

        Pcb.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        Pcb.setForeground(new java.awt.Color(190, 156, 199));
        Pcb.setText("Bar code:");
        Pcb.setToolTipText("");
        Pcb.setBorder(null);
        Pcb.setDisabledTextColor(new java.awt.Color(151, 153, 155));
        Pcb.setDragEnabled(true);
        Pcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PcbActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        Pqty.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        Pqty.setForeground(new java.awt.Color(190, 156, 199));
        Pqty.setText("Qty:");
        Pqty.setToolTipText("");
        Pqty.setBorder(null);
        Pqty.setDisabledTextColor(new java.awt.Color(151, 153, 155));
        Pqty.setDragEnabled(true);
        Pqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PqtyActionPerformed(evt);
            }
        });

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));

        Psup.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        Psup.setForeground(new java.awt.Color(190, 156, 199));
        Psup.setText("Supplier ID:");
        Psup.setToolTipText("");
        Psup.setBorder(null);
        Psup.setDisabledTextColor(new java.awt.Color(151, 153, 155));
        Psup.setDragEnabled(true);
        Psup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PsupActionPerformed(evt);
            }
        });

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));

        Pcategory.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        Pcategory.setForeground(new java.awt.Color(190, 156, 199));
        Pcategory.setText("Category:");
        Pcategory.setToolTipText("");
        Pcategory.setBorder(null);
        Pcategory.setDisabledTextColor(new java.awt.Color(151, 153, 155));
        Pcategory.setDragEnabled(true);
        Pcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PcategoryActionPerformed(evt);
            }
        });

        Pcprice.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        Pcprice.setForeground(new java.awt.Color(190, 156, 199));
        Pcprice.setText("Cost price:");
        Pcprice.setToolTipText("");
        Pcprice.setBorder(null);
        Pcprice.setDisabledTextColor(new java.awt.Color(151, 153, 155));
        Pcprice.setDragEnabled(true);
        Pcprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PcpriceActionPerformed(evt);
            }
        });

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(190, 156, 199));
        jLabel3.setText("Supplier name");

        Psn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Psn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supplier" }));
        Psn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(190, 156, 199), 2));
        Psn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PsnMouseClicked(evt);
            }
        });
        Psn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PsnActionPerformed(evt);
            }
        });
        Psn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PsnKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PsnKeyReleased(evt);
            }
        });

        tva.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        tva.setForeground(new java.awt.Color(190, 156, 199));
        tva.setText("TVA");
        tva.setToolTipText("");
        tva.setBorder(null);
        tva.setDisabledTextColor(new java.awt.Color(151, 153, 155));
        tva.setDragEnabled(true);
        tva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvaActionPerformed(evt);
            }
        });
        tva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tvaKeyReleased(evt);
            }
        });

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));

        Pprice.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        Pprice.setForeground(new java.awt.Color(190, 156, 199));
        Pprice.setText("Sell price:");
        Pprice.setToolTipText("");

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));

        Psname.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        Psname.setForeground(new java.awt.Color(190, 156, 199));
        Psname.setText("Supplier name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Psup, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pqty, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pname, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pcprice, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Psn, 0, 229, Short.MAX_VALUE))
                                .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator13, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Pcb, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 211, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Psname)
                            .addComponent(Pprice))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Bsave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bsearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bupdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bdelete)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pcprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pprice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Psup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Psn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(Psname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bsave)
                    .addComponent(Bsearch)
                    .addComponent(Bupdate)
                    .addComponent(Bdelete))
                .addGap(45, 45, 45))
        );

        Ptable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Ptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nom de produit", "Code a barre", "Prix de revient", "Prix de vente", "Qty", "Categoie", "Fournisseur ID", "Nom de fournisseur", "TVA"
            }
        ));
        Ptable.setGridColor(new java.awt.Color(0, 0, 0));
        Ptable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        Ptable.setShowHorizontalLines(true);
        Ptable.setSurrendersFocusOnKeystroke(true);
        Ptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Ptable);

        Pst.setFont(new java.awt.Font("Segoe UI Black", 0, 13)); // NOI18N
        Pst.setForeground(new java.awt.Color(151, 153, 155));
        Pst.setToolTipText("");
        Pst.setBorder(null);
        Pst.setDisabledTextColor(new java.awt.Color(151, 153, 155));
        Pst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PstActionPerformed(evt);
            }
        });
        Pst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PstKeyReleased(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(400, 400, 400)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(515, 515, 515)
                .addComponent(jLabel4)
                .addContainerGap(414, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(0, 67, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(Pst, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(127, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 584, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(Pst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(283, 283, 283)
                            .addComponent(jLabel5))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PsidActionPerformed

    }//GEN-LAST:event_PsidActionPerformed

    private void PnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PnameActionPerformed

    }//GEN-LAST:event_PnameActionPerformed

    private void PnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PnameKeyReleased
        try{
            String name = Pname.getText();

            Statement s = Bd.mycon().createStatement();
            ResultSet rs = s.executeQuery("SELECT Product_name FROM product");
            while (rs.next()){
                if (name.equals(rs.getString("Product_name"))){
                    JOptionPane.showMessageDialog(null,("Produit deja existe "));
                }
            }
        }catch(Exception e){
        }
    }//GEN-LAST:event_PnameKeyReleased

    private void BsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsaveActionPerformed

        String name = Pname.getText();
        String bcode = Pcb.getText();
        String cprice = Pcprice.getText();
        String Tva = tva.getText();
        String price = Pprice.getText();
        String qty = Pqty.getText();
        String category = Pcategory.getText();
        String sid = Psup.getText();
        String sname = Psn.getSelectedItem().toString();

        try{
            Statement s = Bd.mycon().createStatement();
            s.executeUpdate(" INSERT INTO product (Product_name,Bar_code,Cost_price,Price,Qty,Category,SID,SName,TVA) VALUES ('"+name+"','"+bcode+"','"+cprice+"','"+price+"','"+qty+"','"+category+"','"+sid+"','"+sname +"','"+Tva+"')");
            JOptionPane.showMessageDialog(null,("Data saved"));
        }catch(SQLException e ){
            System.out.println(e);
        }
        tb_load();
        verif();
    }//GEN-LAST:event_BsaveActionPerformed

    private void BsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsearchActionPerformed

        String search = Psid.getText();
        try{
            Statement s = Bd.mycon().createStatement();
            ResultSet rs = s.executeQuery(" SELECT * FROM product WHERE Pid = '"+search+"' ");
            if (rs.next()){
                Pname.setText(rs.getString("Product_name"));
                Pcb.setText(rs.getString("Bar_code"));
                Pcprice.setText(rs.getString("Cost_price"));
                Pprice.setText(rs.getString("Price"));
                Pqty.setText(rs.getString("Qty"));
                Pcategory.setText(rs.getString("Category"));
                Psup.setText(rs.getString("SID"));
                Psn.setSelectedItem(rs.getString("SName"));
                tva.setText(rs.getString("TVA"));
            }
        }catch(SQLException e){
            System.out.println(e);
        }
        tb_load();
    }//GEN-LAST:event_BsearchActionPerformed

    private void BupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BupdateActionPerformed

        String name = Pname.getText();
        String bcode = Pcb.getText();
        String cprice = Pcprice.getText();
        String price = Pprice.getText();
        String qty = Pcategory.getText();
        String category = Pqty.getText();
        String sid = Psup.getText();
        String sname = Psn.getSelectedItem().toString();
        String id = Psid.getText();
        String Tva = tva.getText();
        try {
            Statement s = Bd.mycon().createStatement();
            s.executeUpdate(" UPDATE product SET Product_name = '"+name+"' , Bar_code = '"+bcode+"', Cost_price = '"+cprice+"', Price = '"+price+"', Qty = '"+qty+"',Category = '"+category+"', SID = '"+sid+"', SName = '"+sname+"',TVA ='"+Tva+"' WHERE Pid = '"+id+"' ");
            JOptionPane.showMessageDialog(null,("Data updated"));
        }catch(Exception e){
            System.out.println(e);
        }
        tb_load();
    }//GEN-LAST:event_BupdateActionPerformed

    private void BdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdeleteActionPerformed

        String id = Psid.getText();
        try {
            Statement s = Bd.mycon().createStatement();
            s.executeUpdate(" DELETE FROM product WHERE Pid = '"+id+"' ");
            JOptionPane.showMessageDialog(null,("Data deleted"));

        }catch (Exception e){
            System.out.println(e);
        }
        tb_load();
    }//GEN-LAST:event_BdeleteActionPerformed

    private void PcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PcbActionPerformed

    }//GEN-LAST:event_PcbActionPerformed

    private void PqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PqtyActionPerformed

    }//GEN-LAST:event_PqtyActionPerformed

    private void PsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PsupActionPerformed

    }//GEN-LAST:event_PsupActionPerformed

    private void PcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PcategoryActionPerformed

    }//GEN-LAST:event_PcategoryActionPerformed

    private void PcpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PcpriceActionPerformed

    }//GEN-LAST:event_PcpriceActionPerformed

    private void PsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PsnActionPerformed
        try{
            Statement s = Bd.mycon().createStatement();
            ResultSet rs = s.executeQuery(" SELECT * FROM supplier WHERE  Supplier_name = '"+Psn.getSelectedItem().toString()+"' ");
            if(rs.next()){
                Psup.setText(rs.getString("Sid"));
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_PsnActionPerformed

    private void tvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvaActionPerformed

    }//GEN-LAST:event_tvaActionPerformed

    private void tvaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tvaKeyReleased
        Price();
    }//GEN-LAST:event_tvaKeyReleased

    private void PtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PtableMouseClicked

        int r = Ptable.getSelectedRow();
        String id = Ptable.getValueAt(r,0).toString();
        String name = Ptable.getValueAt(r,1).toString();
        String barcode = Ptable.getValueAt(r,2).toString();
        String cprice = Ptable.getValueAt(r,3).toString();
        String price = Ptable.getValueAt(r,4).toString();
        String qty = Ptable.getValueAt(r,5).toString();
        String category = Ptable.getValueAt(r,6).toString();
        String sid = Ptable.getValueAt(r,7).toString();
        String sname = Ptable.getValueAt(r,8).toString();
        String Tva = Ptable.getValueAt(r,9).toString();
        Psid.setText(id);
        Pname.setText(name);
        Pcb.setText(barcode);
        Pcprice.setText(cprice);
        Pprice.setText(price);
        Pqty.setText(qty);
        Pcategory.setText(category);
        Psup.setText(sid);
        Psname.setText(sname);
        tva.setText(Tva);
    }//GEN-LAST:event_PtableMouseClicked

    private void PstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PstActionPerformed

    }//GEN-LAST:event_PstActionPerformed

    private void PstKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PstKeyReleased
        // search in table here :
        String name = Pst.getText();
        try{
            DefaultTableModel dt = (DefaultTableModel) Ptable.getModel();
            Statement s = Bd.mycon().createStatement();
            dt.setRowCount(0);
            ResultSet rs = s.executeQuery(" SELECT * FROM product WHERE Product_name LIKE '%"+name+"%'  ");
            while (rs.next()){
                Vector v = new Vector ();
                v.add(rs.getString(1));
                v.add(rs.getString(2));
                v.add(rs.getString(3));
                v.add(rs.getString(4));
                v.add(rs.getString(5));
                v.add(rs.getString(6));
                v.add(rs.getString(7));
                v.add(rs.getString(8));
                v.add(rs.getString(9));
                v.add(rs.getString(10));
                dt.addRow(v);
            }
        }catch (Exception e){
            tb_load();
        }
    }//GEN-LAST:event_PstKeyReleased

    private void PsnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PsnKeyReleased

    }//GEN-LAST:event_PsnKeyReleased

    private void PsnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PsnKeyPressed
     
    }//GEN-LAST:event_PsnKeyPressed

    private void PsnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PsnMouseClicked
        String Sname = Psn.getSelectedItem().toString();
      Psname.setText(Sname);
    }//GEN-LAST:event_PsnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bdelete;
    private javax.swing.JButton Bsave;
    private javax.swing.JButton Bsearch;
    private javax.swing.JButton Bupdate;
    private javax.swing.JTextField Pcategory;
    private javax.swing.JTextField Pcb;
    private javax.swing.JTextField Pcprice;
    private javax.swing.JTextField Pname;
    private javax.swing.JLabel Pprice;
    private javax.swing.JTextField Pqty;
    private javax.swing.JTextField Psid;
    private javax.swing.JComboBox<String> Psn;
    private javax.swing.JLabel Psname;
    private javax.swing.JTextField Pst;
    private javax.swing.JTextField Psup;
    private javax.swing.JTable Ptable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField tva;
    // End of variables declaration//GEN-END:variables
}
